import type { ConceptRoute } from "./types";

// Pure, client-safe formatters. Used by copy-to-clipboard and the export buttons.

export function routeToMarkdown(r: ConceptRoute): string {
  const lines = [
    `## ${r.concept_name || r.route_name}`,
    r.route_rationale ? `_${r.route_rationale}_` : "",
    "",
    `**Insight** — ${r.insight}`,
    `**Benefit** — ${r.benefit}`,
    `**RTB** — ${r.rtb}`,
    `**Tagline** — ${r.tagline}`,
    r.claim ? `**Claim** — ${r.claim}` : "",
    "",
    `**Screener readiness:** ${r.rule_check.overall_readiness}/100`,
  ];
  return lines.filter((l) => l !== "").join("\n");
}

export function routesToMarkdown(routes: ConceptRoute[]): string {
  const header = `# Concept Routes\n\n_Generated by the Concept Writing Assistant_\n`;
  return header + "\n\n---\n\n" + routes.map(routeToMarkdown).join("\n\n---\n\n");
}

export function downloadText(filename: string, content: string, mime = "text/markdown") {
  const blob = new Blob([content], { type: `${mime};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

// Minimal Word-openable export: an .doc HTML file (opens cleanly in Word).
export function routesToWordHtml(routes: ConceptRoute[]): string {
  const body = routes
    .map(
      (r) => `
    <h2>${escapeHtml(r.concept_name || r.route_name)}</h2>
    <p><em>${escapeHtml(r.route_rationale)}</em></p>
    <p><strong>Insight:</strong> ${escapeHtml(r.insight)}</p>
    <p><strong>Benefit:</strong> ${escapeHtml(r.benefit)}</p>
    <p><strong>RTB:</strong> ${escapeHtml(r.rtb)}</p>
    <p><strong>Tagline:</strong> ${escapeHtml(r.tagline)}</p>
    ${r.claim ? `<p><strong>Claim:</strong> ${escapeHtml(r.claim)}</p>` : ""}
    <p><strong>Screener readiness:</strong> ${r.rule_check.overall_readiness}/100</p>
    <hr/>`
    )
    .join("");
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Concept Routes</title></head>
  <body style="font-family:Georgia,serif;line-height:1.5">
  <h1>Concept Routes</h1>${body}</body></html>`;
}

function escapeHtml(s: string): string {
  return (s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}
